@startuml
title Нарезка дизайна
start
repeat
:Выбираем слой, для которого
не делалось срезов;
  :Получаем координаты вершин Х и Y 
  всех прямоугольников слоя;
  :Сортируем координаты, 
  удаляем дублирующиеся;
  repeat
    :Выбираем координату Х, 
    по которй не делалось среза;
    :Делаем вертикальный срез,
    захватывая два слоя сверху 
    и два слоя снизу (если они есть);
    :Сохраняем в формат
    AppCap2d и FasterCap.
    Имена файлов для сохранения:
    N_X_0.in, N_X_0.lst;
  repeat while (Есть ли еще координаты X?)
  repeat
    :Выбираем координату Y, 
    по которй не делалось среза;
    :Делаем горизонтальный срез,
    захватывая два слоя сверху 
    и два слоя снизу (если они есть);
    :Сохраняем в формат
    AppCap2d и FasterCap.
    Имена файлов для сохранения:
    N_0_Y.in, N_0_Y.lst;
  repeat while (Есть ли еще координаты Y?)
repeat while (Есть ли еще слои?)
stop
@enduml